### ISSUE TITLE
Add Italian and Spanish packages

### ISSUE THREAD

**Issue by akira28** [yireo/magento-ce-languagefiles#2]
As I've seen on the Transifex project, both Italian and Spanish locales are ready (98%).
Would it be possible to add them to this repo?

**Comment by yireo** [comment]
Yes, definitely. I found out that our cronjob to automatically add new packages was not working for a few weeks. This has now been fixed and you should be able to see your new language packs in the packages/ folder within 10 minutes or so.

**Comment by akira28** [comment]
Fantastic, I close the issue.
